In [1]:
# based on the article posted on http://iamtrask.github.io/2015/07/12/basic-python-network/

In [2]:
import numpy as np
np.random.seed(21)

In [3]:
#sigmoid function
def sigmoid(x, deriv = False):
    '''defining a function for non-linearity
    A sigmoid function maps any value to a value between 0 and 1
    it is used to convert numbers into probablities.
    there are many such functions example 'tanh

    args: deriv
    a derivative is the slope of sigmoid function at any given time
    '''
    
    if(deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    


In [4]:
# input layer-->numpy matrix
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print(x)
print("shape of x", x.shape)
print("we have 3 input nodes and four training examples")

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
shape of x (4, 3)
we have 3 input nodes and four training examples


In [5]:
# output layer-->numpy matrix
y = np.array([[0,0,1,1]]).T
print(y)
print("shape of y", y.shape)


[[0]
 [0]
 [1]
 [1]]
shape of y (4, 1)


In [6]:
# random initialisation of synaptic weights
# size of synaptic weight is (3,1) because we have 3 input nodes and one output node
# also it is initialised with mean of zero
# input dimension x synaptic weight = output dimension
#        4*3      x       3*1       =       4*1


synaptic_weights = 2*np.random.random((3,1)) - 1 

In [7]:
# looping with full batch training
# all the input trained in a single batch

for i in range(100000):
    # we have 2 layers only- input and output
    
    # step 1 - forward propogation
    layer0 = x
    layer1 = sigmoid(np.dot(layer0, synaptic_weights))
    
    # calculating the error
    layer1_error = y - layer1
    
    # step 2 - multiply how much we missed with the slope of the sigmoid at the values in layer1
    layer1_delta = layer1_error * sigmoid(layer1, True)
    
    # updating the weights
    synaptic_weights += np.dot(layer0.T, layer1_delta)
    
print("final output")
print(layer1)

final output
[[ 0.00301783]
 [ 0.00246106]
 [ 0.99799167]
 [ 0.99753707]]
